/**
 * Authz sweep (Ticket 1.18): lists every server action and route handler with
 * the guard it calls first, so the "every mutation is guarded" rule can be
 * audited at a glance. Writes docs/authz-sweep.md.
 *
 *   node scripts/authz-sweep.mjs            → writes the doc
 *   node scripts/authz-sweep.mjs --check    → exits 1 if any export has no guard
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from "node:fs";
import { join, relative } from "node:path";

const root = new URL("..", import.meta.url).pathname.replace(/^\/([A-Za-z]:)/, "$1");
const src = join(root, "src");
const GUARDS =
  /\b(requireSession|requireTeacher|requireStudent|requireOwner|requireShared|requireEnrolled|requireAssignmentAccess|requireAttemptAccess|requireContentAccess|requirePracticeAttemptAccess|publicRoute|publicAction)\b/;

function walk(dir, out = []) {
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) walk(p, out);
    else if (/\.(ts|tsx)$/.test(name) && !/\.test\.tsx?$/.test(name)) out.push(p);
  }
  return out;
}

/** Split a file into top-level `export const NAME = ...` blocks (server actions) or `export const GET/POST` (routes). */
function exportBlocks(text) {
  const blocks = [];
  const re = /^export (?:const|async function|function) (\w+)/gm;
  let m;
  const starts = [];
  while ((m = re.exec(text))) starts.push({ name: m[1], at: m.index });
  for (let i = 0; i < starts.length; i++) {
    const end = i + 1 < starts.length ? starts[i + 1].at : text.length;
    blocks.push({ name: starts[i].name, body: text.slice(starts[i].at, end) });
  }
  return blocks;
}

const rows = [];
let missing = 0;
for (const file of walk(src)) {
  const text = readFileSync(file, "utf8");
  const isServer = /^\s*["']use server["']/m.test(text);
  const isRoute = /[\\/]route\.ts$/.test(file);
  if (!isServer && !isRoute) continue;
  for (const b of exportBlocks(text)) {
    if (isRoute && !/^(GET|POST|PUT|PATCH|DELETE|HEAD|OPTIONS)$/.test(b.name)) continue;
    if (isServer && !/withAuthz\(|publicAction\(/.test(b.body) && !/async/.test(b.body)) continue;
    if (isServer && /^export type /.test(b.body)) continue;
    const guard = b.body.match(GUARDS)?.[1] ?? null;
    if (!guard) missing++;
    const perm =
      guard === "requireShared"
        ? (b.body.match(/requireShared\([^)]*?,\s*"(\w+)"\)/)?.[1] ?? "")
        : "";
    rows.push({
      file: relative(root, file).replace(/\\/g, "/"),
      name: b.name,
      kind: isRoute ? "route" : "action",
      guard: guard ? (perm ? `${guard}(${perm})` : guard) : "NONE",
    });
  }
}
rows.sort((a, b) => a.file.localeCompare(b.file) || a.name.localeCompare(b.name));

const lines = [
  "# Authorization sweep",
  "",
  `Generated by \`node scripts/authz-sweep.mjs\` on ${new Date().toISOString().slice(0, 10)}. Every server action and route handler, with the first guard it calls. \`publicRoute\` / \`publicAction\` mark the few intentionally open entry points; everything else must name a \`require*\` guard (the ESLint rule \`bloom/require-authz\` fails the build otherwise).`,
  "",
  `${rows.length} entry points · ${rows.filter((r) => r.guard === "NONE").length} without a guard.`,
  "",
  "| File | Export | Kind | Guard |",
  "| --- | --- | --- | --- |",
  ...rows.map((r) => `| ${r.file} | ${r.name} | ${r.kind} | ${r.guard} |`),
  "",
  "## Tier 1 integrity checks (PLAN.md §6) and where they are proven",
  "",
  "| Check | Enforced in | Test |",
  "| --- | --- | --- |",
  '| Window (opens / closes) | `canStartAttempt` in src/lib/assignments.ts, called by `startAttempt` | src/lib/assignments.test.ts "blocks outside the window"; src/app/app/assign/actions.test.ts "an enrolled student sees the assignment inside its window" |',
  '| Access code | `canStartAttempt` (`codesMatch`) | src/lib/assignments.test.ts "requires the access code when set"; src/app/student/actions.test.ts "enforces enrollment, role, and the access code" |',
  '| Roster-only access | `requireAssignmentAccess` / `requireEnrolled` in src/lib/authz.ts | src/lib/authz.test.ts; src/app/student/actions.test.ts "enforces enrollment, role, and the access code" |',
  '| Attempt limits | `canStartAttempt` (`attemptsUsed` vs `attemptsAllowed`) | src/lib/assignments.test.ts "stops at the attempt limit"; src/app/student/actions.test.ts "a third is refused" |',
  '| Server-side time | `attemptDueAt` + `writableAttempt` (saves refused after due + 5 s), autosubmit on return | src/lib/assignments.test.ts "start + limit, scaled by extra time"; src/app/student/actions.test.ts "rejects saves after the deadline" and "auto-submitted when the student comes back" |',
  '| Scores written only by server code | `src/lib/attempts.ts` (`finalizeAttempt`); student actions store answers only | src/app/student/actions.test.ts "grades every served question" |',
  "| Student payload carries no keys | `sanitizedQuestions` in src/lib/queries/attempts.ts | src/app/student/actions.test.ts (runner payload assertions) |",
  "",
];
writeFileSync(join(root, "docs", "authz-sweep.md"), lines.join("\n"));
console.log(`${rows.length} entry points, ${missing} without a guard → docs/authz-sweep.md`);
if (process.argv.includes("--check") && missing > 0) process.exit(1);
